-- create TABLE dungeons(
--     -- id SERIAL PRIMARY KEY,
--     -- name ,
--     -- surname VARCHAR(255)
--     title VARCHAR(50),
--     type VARCHAR(10),
--     desc VARCHAR(255),
--     time-open VARCHAR(25),
--     difficulty INTEGER,
--     award-percents INTEGER,
--     award VARCHAR[],
--     number-items INTEGER,
--     img VARCHAR(255),
--     banerImg VARCHAR(255),
--     id SERIAL PRIMARY KEY;
-- );

-- -- create TABLE post(
-- --     id SERIAL PRIMARY KEY,
-- --     title VARCHAR(255),
-- --     content VARCHAR(255),
-- --     user_id INTEGER,
-- --     FOREIGN KEY (user_id) REFERENCES person (id)
-- -- );

